// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package src

import "fyne.io/fyne/v2"

// 爱心
var ResourceLoveSvg = &fyne.StaticResource{
	StaticName: "Love.svg",
	StaticContent: []byte(
		`<?xml version="1.0" standalone="no"?><!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd"><svg t="1684654314606" class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" p-id="2039" xmlns:xlink="http://www.w3.org/1999/xlink" width="200" height="200"><path d="M512 910.68S-107.66 456.37 110.56 215.3s401.55 20.88 401.55 20.88 183.38-259.66 401.4-20.88S512 910.68 512 910.68z" fill="#FF716E" p-id="2040"></path><path d="M512.11 236.18s-18.61-26.58-51-55c-128.9 80.55-214.66 223.74-214.66 387a456.34 456.34 0 0 0 16.4 121.56C382.56 815.76 512 910.68 512 910.68s619.49-456.6 401.48-695.38-401.37 20.88-401.37 20.88z" fill="#FF5C64" p-id="2041"></path><path d="M416.6 707.53a455.39 455.39 0 0 0 24.2 147c42.68 35.22 71.2 56.15 71.2 56.15s552.8-407.42 430.27-653.81a459.12 459.12 0 0 0-69.71-5.3c-251.82 0-455.96 204.14-455.96 455.96z" fill="#FC4956" p-id="2042"></path><path d="M958.57 359.37c-224.11 28.79-397.3 220.28-397.3 452.22a460.12 460.12 0 0 0 3.62 57.72c113.53-92.17 372.22-321.14 393.68-509.94z" fill="#F23D4F" p-id="2043"></path><path d="M306.38 189.08c7.56 11.35-32.21 25.37-74.16 53.32s-70.2 59.26-77.76 47.91 15.63-50.24 57.59-78.19 86.77-34.38 94.33-23.04z" fill="#FFFFFF" p-id="2044"></path></svg>`),
}
